-- Create learnings table in Supabase
create table public.learnings (
  id bigint generated by default as identity primary key,
  project_uuid uuid default gen_random_uuid(),
  conversation_id uuid not null,
  author text not null,
  type text not null check (type in (
    'SCOPING',
    'DESIGN-FRICTION',
    'THEORETICAL',
    'TECHNICAL',
    'HALLUCINATION',
    'METACOGNITIVE',
    'VALIDATION',
    'ERROR-CODE',
    'FRUSTRATION'
  )),
  skill text not null default 'skill-weave',
  section text,
  key text not null unique,
  insight text not null, -- Roadblock (Specific Incident)
  example text,          -- Resolution / Steer Fix
  metacognitive_pattern text, -- Generalized pattern (e.g. Monolith Scoping)
  socratic_pivot text,   -- Socratic Pivot Questions (Domain-Agnostic)
  model text not null default 'gemini-2.0-pro',
  source text not null default 'USER',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table public.learnings enable row level security;

-- Create policies for public access using the anon API key
create policy "Allow public select" on public.learnings
  for select using (true);

create policy "Allow public insert" on public.learnings
  for insert with check (true);
